env:
  global:
  - REPO=snaxfoundation/snaxtracker
language: node_js
node_js:
- "10"

install:
- npm i

services:
- docker

script:
- npx ng build --prod
- docker build -t $REPO:$TRAVIS_BRANCH .
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push $REPO:$TRAVIS_BRANCH
