env:
  global:
  - REPO=snaxfoundation/snaxtracker
language: node_js
node_js:
- "10"

install:
- npm i

services:
- docker

script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit 0;fi
- npx ng build --prod
- docker build -t $REPO:$TRAVIS_BRANCH .
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push $REPO:$TRAVIS_BRANCH
- curl --write-out '%{http_code}' --silent --output /dev/null -X POST -F token=$TOKEN -F ref=$TRAVIS_BRANCH $URL